[package]
name = "simple_rust_timer"
version = "0.1.0"
authors = ["Ole"]
edition = "2018"

[dependencies]
chrono = "0.4.10"
crossterm = "0.14.1"

[target.'cfg(target_os = "linux")'.dependencies]
notify-rust = "3.6.3"
